version: '3'
services:
  web:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/code
      - ./data:/data
    env_file: .env
    depends_on:
      - db
  db:
    image: postgres
    env_file: .env
    environment:
      - POSTGRES_DB=class_util_db
