# Generated by Django 2.1.4 on 2018-12-10 04:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('department', models.CharField(max_length=8)),
                ('number', models.PositiveIntegerField()),
                ('title', models.CharField(max_length=200)),
                ('hours', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
            ],
            options={
                'ordering': ['department', 'number', 'title', 'hours'],
            },
        ),
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('CRN', models.PositiveIntegerField()),
                ('instructor', models.CharField(max_length=30)),
                ('average_GPA', models.DecimalField(decimal_places=2, max_digits=4)),
                ('As', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Bs', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Cs', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Ds', models.DecimalField(decimal_places=1, max_digits=4)),
                ('Fs', models.DecimalField(decimal_places=1, max_digits=4)),
                ('withdrawals', models.PositiveIntegerField()),
                ('class_size', models.PositiveIntegerField()),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='distributions.Course')),
            ],
            options={
                'ordering': ['term', 'course', 'CRN', 'instructor', 'average_GPA'],
            },
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('ordering', models.PositiveIntegerField()),
            ],
            options={
                'ordering': ['ordering'],
            },
        ),
        migrations.CreateModel(
            name='Term',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.PositiveIntegerField()),
                ('semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='distributions.Semester')),
            ],
            options={
                'ordering': ['year', 'semester'],
            },
        ),
        migrations.AddField(
            model_name='section',
            name='term',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='distributions.Term'),
        ),
    ]
