# Generated by Django 2.1.4 on 2019-03-26 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('distributions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pathway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('description', models.CharField(max_length=100)),
                ('courses', models.ManyToManyField(related_name='pathways', to='distributions.Course')),
            ],
            options={
                'ordering': ('name', 'description'),
            },
        ),
    ]
